### ISSUE TITLE
New account workflow problems

### ISSUE THREAD

**Issue by LosAlamosAl** [mcpherson/AWS-book-finder#5]
App is working great. Just a few issues when signing up for a new account:

1. The email in which the verification code is sent has **no** identification that it's from Bookfinder or `mcpherson.dev`. Should show a recognizable from address or state that it's a Bookfinder signup code in the body of the email.
2. After login to new account you're sent to the Library page. Text says that "Images are loading...". Of course they never show up because none have been uploaded yet.
3. After uploading images, and going to Library page, "Loading images..." is shown yet they never show. Hard reload of page (Shift-reload) loads the images.

**Comment by LosAlamosAl** [comment]
Another one:

4. After logout, going to Login page shows wrong default address/password in boxes. Something isn't getting cleared. Maybe not show a default at all?

**Comment by mcpherson** [comment]
All issues fixed or negated.
